using KursALX.Assigments;
using KursALX.Assigments.M2;
using KursALX.Lessons;
using KursALX.Lessons.M1.L1;
using KursALX.Lessons.M1.L2;
using KursALX.Lessons.M2.L1;

//Console.Write("Emil Pałczyński\n");
Console.WriteLine("KursALX");
Console.WriteLine("----------------------------");
//L1Lists.Run();
//L1Arrays.Run1();
//L1Arrays.Run();
//SeniorityServiceTest.Run();
//Console.WriteLine("Lekcja 1");
//L1ObjectVariables.Run2();
//L1ObjectVariables l1variables = new L1ObjectVariables();
//l1variables.WriteSomething();
//L1SimpleVariables.Run();
//L1Strings.Run();
//L1Strings.ConcatinationTest();
//L1Constructors.Run();
//AssigmentsDemo.Run();
//L2Conditionals.Run();
//L2EnumsAndSwitch.Run();
Console.WriteLine("----------------------------");
