using KursALX.Assigments;
using KursALX.Lessons;
using KursALX.Lessons.L1;
using KursALX.Lessons.L2;

//Console.Write("Emil Pałczyński\n");
Console.WriteLine("KursALX");
Console.WriteLine("----------------------------");
//Console.WriteLine("Lekcja 1");
//L1ObjectVariables.Run2();
//L1ObjectVariables l1variables = new L1ObjectVariables();
//l1variables.WriteSomething();
//L1SimpleVariables.Run();
//L1Strings.Run();
//L1Strings.ConcatinationTest();
//L1Constructors.Run();
//AssigmentsDemo.Run();
//L2Conditionals.Run();
//L2EnumsAndSwitch.Run();
Console.WriteLine("----------------------------");
